version: "3.2"
services:
  movetain:
    build: .
    volumes:
      - ./secrets:/movetain/secrets
  nginx:
    image: nginx:1.18
    ports:
      - "80:80"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
