version: "3.2"
services:
  movetain:
    build: .
    volumes:
      - ./secrets:/movetain/secrets
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    expose:
      - 8080
